[package]
name = "boo-language"
version.workspace = true
edition.workspace = true

[lib]
bench = false

[dependencies]
boo-core = { path = "../core" }

proptest = "1.3.1"
proptest-derive = "0.4.0"

[package.metadata.cargo-machete]
ignored = ["proptest"]
