[package]
name = "boo-language"
version.workspace = true
edition.workspace = true

[lib]
bench = false

[dependencies]
boo-core = { path = "../core" }

proptest = "1.2.0"
proptest-derive = "0.3.0"

[package.metadata.cargo-machete]
ignored = ["proptest"]
