[package]
name = "boo-evaluation-reduction"
version.workspace = true
edition.workspace = true

[lib]
bench = false

[dependencies]
boo-core = { path = "../core" }

im = { version = "15.1.0", features = ["proptest"] }
