[package]
name = "boo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
miette = { version = "5.8.0", features = ["fancy"] }
peg = "0.8.1"
reedline = "0.18.0"
thiserror = "1.0.40"

[dev-dependencies]
arbitrary = { version = "1.3.0", features = ["derive"] }
arbtest = "0.2.0"
