[package]
name = "boo-naive-evaluator"
version = "0.1.0"
edition = "2021"

[dependencies]
boo-core = { path = "../core" }
boo-parser = { path = "../parser" }

im = { version = "15.1.0", features = ["proptest"] }
