[package]
name = "boo-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
boo-core = { path = "../core" }
boo-fill-hole = { path = "../fill-hole" }
boo-lexer = { path = "../lexer" }

im = { version = "15.1.0", features = ["proptest"] }
peg = "0.8.1"
proptest = "1.1.0"
proptest-derive = "0.3.0"

[dev-dependencies]
boo-test-helpers = { path = "../test-helpers" }
