[package]
name = "boo-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
boo-core = { path = "../core" }
boo-lexer = { path = "../lexer" }

peg = "0.8.1"

[dev-dependencies]
boo-generator = { path = "../generator" }
boo-test-helpers = { path = "../test-helpers" }

proptest = "1.1.0"
