[package]
name = "boo-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
boo-core = { path = "../core" }

im = { version = "15.1.0", features = ["proptest"] }
proptest = "1.1.0"
proptest-derive = "0.3.0"
