[package]
name = "boo-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
boo-core = { path = "../core" }

logos = "0.13.0"

[dev-dependencies]
boo-test-helpers = { path = "../test-helpers" }
proptest = "1.1.0"
proptest-derive = "0.3.0"
