[package]
name = "boo-random-program"
version.workspace = true
edition.workspace = true

[[bin]]
name = "random-program"
path = "src/main.rs"
bench = false

[dependencies]
boo = { path = "../lib" }
boo-generator = { path = "../generator" }

anyhow = "1.0.72"
proptest = "1.2.0"
