[package]
name = "boo-core"
version = "0.1.0"
edition = "2021"

[dependencies]
boo-fill-hole = { path = "../fill-hole" }

lazy_static = "1.4.0"
miette = { version = "5.8.0" }
num-bigint = "0.4.0"
proptest = "1.1.0"
proptest-derive = "0.3.0"
regex = "1.8.1"
thiserror = "1.0.40"

[dev-dependencies]
boo-test-helpers = { path = "../test-helpers" }
