[package]
name = "boo-interpreter"
version = "0.1.0"
edition = "2021"

default-run = "interpreter"

[[bin]]
name = "interpreter"
path = "src/main.rs"
bench = false

[dependencies]
boo = { version = "0.1.0", path = "../lib" }
boo-naive-evaluator = { version = "0.1.0", path = "../naive-evaluator" }

anyhow = "1.0.71"
atty = "0.2.14"
clap = { version = "4.3.9", features = ["derive"] }
miette = { version = "5.8.0", features = ["fancy"] }
reedline = "0.18.0"
